site_name: TACS文档
site_url: https://docs.tacs.top
repo_url: https://github.com/TAC-Server/docs/
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2016 - Now <a href="https://space.bilibili.com/1546229901"><b>Redapple_one</b></a>
extra_css:
  - stylesheets/font.css
  - stylesheets/color.css
  - stylesheets/admonitions.css
extra:
  social:
    - icon: simple/bilibili
      link: https://space.bilibili.com/1546229901
      name: Redapple_one的B站账号
    - icon: simple/youtube
      link: https://github.com/TAC-Server
      name: Github上的TAC-Server组织
    - icon: simple/github
      link: https://www.youtube.com/@Redapple_one
      name: Redapple_one的YouTube账号
    - icon: simple/maildotru
      link: mailto:3134641406@qq.com
      name: 给Redapple_one发邮件
plugins:
  - search
  - meta
  - awesome-nav
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
  - glightbox
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
theme:
  name: material
  favicon: https://img.fastmirror.net/s/2025/04/24/680a354f7ace6.png
  logo: https://img.fastmirror.net/s/2025/08/02/688db8fccea64.png
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    repo: fontawesome/brands/github
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  custom_dir: overrides
  features:
    - content.action.edit
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - navigation.sections
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
  language: zh
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: 切换到浅色模式

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: 切换到自动
watch:
  - includes